import Head from 'next/head';
import styles from './index.module.scss';

import Cards from 'components/HomeCard/cards';
import Products from 'components/HomeProducts';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>eclipse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className={styles.emoji}>🌙</span>New In
        </h1>

        <Products>
          <Cards bgColor="#f6f6f6" />
          <Cards bgColor="#f6f6f6" />
          <Cards bgColor="#f6f6f6" />
        </Products>
        <Products>
          <Cards bgColor="#f6f6f6" />
          <Cards bgColor="#f6f6f6" />
          <Cards bgColor="#f6f6f6" />
        </Products>
      </main>
    </div>
  );
}
