import Head from 'next/head';
import styles from './index.module.scss';

import Cards from 'components/HomeCard/cards';
import Products from 'components/HomeProducts';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>eclipse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className={styles.emoji}>🌙</span>New In
        </h1>

        <Products>
          <Cards
            name="METALL LOGO T-SHIRT"
            image="https://i.pinimg.com/originals/62/98/b0/6298b026a65cf80bcf9dce061e9b79c9.png"
            price="60"
          />
          <Cards
            name="BLUE SIMPLE HOODIE"
            image="https://ramptshirts.com/assets/images/samples/standard-hoodies/red.png"
            price="120"
          />
          <Cards
            name="SOLID WHITE T-SHIRT"
            image="https://pngimg.com/uploads/tshirt/tshirt_PNG5429.png"
            price="60"
          />
        </Products>
        <Products>
          <Cards bgColor="#0C0C0C" />
          <Cards bgColor="#0C0C0C" />
          <Cards bgColor="#0C0C0C" />
        </Products>
      </main>
    </div>
  );
}
